 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package treasurehunt;

/**
 *
 * @author Christopher
 */
public class THUI extends javax.swing.JFrame {

    /**
     * Creates new form THUI
     */
    public THUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outputDisp = new javax.swing.JTextArea();
        inputField = new javax.swing.JTextField();
        inputButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputDisp.setEditable(false);
        outputDisp.setColumns(20);
        outputDisp.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        outputDisp.setRows(5);
        jScrollPane1.setViewportView(outputDisp);

        inputField.setEditable(false);
        inputField.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        inputButton.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        inputButton.setText("Enter");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(inputButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {inputButton, inputField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
        flag = true;
        System.out.println("Button Push");
    }//GEN-LAST:event_inputButtonActionPerformed

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        flag = true;
        System.out.println("Enter Push");
    }//GEN-LAST:event_inputFieldActionPerformed

    public String getCommand(){
        flag = false;
        inputField.setEditable(true);
        while(!flag) {
            try {
		Thread.sleep(4000);
            } catch (InterruptedException e) {
		e.printStackTrace();
            }
        }
        String text = inputField.getText();
        inputField.setText("");
        inputField.setEditable(false);
        return text;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton inputButton;
    public javax.swing.JTextField inputField;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea outputDisp;
    // End of variables declaration//GEN-END:variables
    
    public boolean flag = false;

}
